spring:  
  cloud:
    gateway:
      routes:
      - id: song-service
        uri: http://localhost:9211
        predicates:
        - Path=/song/**

      - id: user-service
        uri: http://localhost:9212
        predicates:
        - Path=/user/**
      
      - id: google-drive-service
        uri: http://localhost:9214
        predicates:
        - Path=/media/**